### ISSUE TITLE
Review maps weighting

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#1]
@keskitalo I've implemented the weighting for all the components,
can you please review that I implemented the weighting as expected?

In particular I assumed that the noise simulations contained just 1 tube.

Executed notebooks with the source of the functions are at:

* https://cmb-s4.github.io/s4_design_sim_tool/foregrounds/
* https://cmb-s4.github.io/s4_design_sim_tool/atmosphere/
* https://cmb-s4.github.io/s4_design_sim_tool/noise/

Feedback either here or you can fix directly the notebook in the root of this repository and make a PR.

No hurry, I'll proceed ahead to assemble the command line tool anyway, and we can merge your feedback/fixes later on.

**Comment by zonca** [comment]
@keskitalo would you take a look at this before next week?

**Comment by keskitalo** [comment]
@zonca can you check the links, I just get an error: 404
There isn't a GitHub Pages site here.

**Comment by zonca** [comment]
@keskitalo it was the package name change, fixed now

**Comment by zonca** [comment]
or you can take a look at the notebooks themselves, e.g. https://github.com/CMB-S4/s4_design_sim_tool/blob/master/01_foregrounds.ipynb

**Comment by keskitalo** [comment]
Thanks @zonca. All three notebooks look great. We should be very explicit about the fact that we assume that atmosphere scales by telescope time, not tube or detector time. We may even be asked to relax that approximation in the future.

**Comment by zonca** [comment]
ok, thanks for reviewing this, added to the docs:

https://cmb-s4.github.io/s4_design_sim_tool/

you can edit `index.ipynb` to improve it.
