### ISSUE TITLE
Save outputs separately

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#10]
@keskitalo @jdborrill 
currently I am saving 1 output map per band per site which includes:
* foreground
* cmb
* atmosphere
* noise
thanks to the configuration file, it is easy to make a different run with no foreground or no cmb, but impossible to make a noiseless run.

I wanted to implement saving all the outputs separately, so:
* foreground
* cmb (includes lensing and tensor modes)
* atmosphere + noise

It increases by a factor of 3 the disk space occupied by the outputs but I think it is worth it. Does it look ok?

**Comment by zonca** [comment]
@cbischoff what do you think about the separation of the outputs I propose above?

**Comment by cbischoff** [comment]
@zonca sounds good. It would be very helpful to have three separate maps for foreground, cmb, and atmosphere+noise.

**Comment by zonca** [comment]
thanks @cbischoff, will do, easiest thing is to reconfigure and rerun the tool, no need to implement this explicitly, so that I keep the code simpler.

**Comment by zonca** [comment]
@cbischoff I put tsz and ksz into the foregrounds map, is that ok or they should be into the CMB?
