### ISSUE TITLE
Location of input folder

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#11]
@keskitalo 
some files in your scratch folder that contains the inputs:

    /global/cscratch1/sd/keskital/s4sim/reference_tool/out

are going to be purged soon,
I am copying the entire folder to:

    /global/cfs/cdirs/cmbs4/dm/dstool/input

But then I realized, do we want instead to use a folder under `www` so that it would be possible to run the tool remotely and download maps on the fly as needed?

/cc @jdborrill

**Comment by keskitalo** [comment]
I think the `www` folder would be appropriate.

**Comment by zonca** [comment]
ok, thanks,
I moved the folder to:

    /global/cfs/cdirs/cmbs4/www/dstool/input

also symlinked from `/global/cfs/cdirs/cmbs4/dm/dstool/input`

it is group writable, so @keskitalo you should be able to write your outputs directly there.

However access via web doesn't work https://portal.nersc.gov/project/cmbs4, I get access denied
@jdborrill I just created the `www` folder myself as it was missing:

```
ls -l /global/cfs/cdirs/cmbs4/www
total 2
drwxrwxr-x 3 cmbs4 cmbs4 4096 May 13 11:09 dstool
-rw-rw-r-- 1 cmbs4 cmbs4   30 May 13 11:12 index.html
```

maybe you need to activate web access within IRIS?

**Comment by jdborrill** [comment]
Please don't make things group-writable.

Write to scratch, move to project as the cmbs4 pseudo-user.

J

**Comment by zonca** [comment]
ok @jdborrill,
as soon as we are done continuously updating stuff I will make everything owned by cmbs4 and remove group-write.

**Comment by zonca** [comment]
@jdborrill can you also please investigate the `www` access forbidden issue? (see above in this issue) otherwise I'll ask consult

**Comment by jdborrill** [comment]
Can you ask consult? I have telecons till late tonight and again from early
morning.

Thanks,

Julian

**Comment by zonca** [comment]
ok, NERSC fixed the issue, this is working now.
