### ISSUE TITLE
Reference design CMB maps

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#12]
@keskitalo @jdborrill @cbischoff 

I am still working on the B-modes, for now I have run CMB with `r=0`,
see the documentation at:

https://github.com/CMB-S4/s4mapbasedsims/blob/master/202004_reference_design/README.md#cmb-no-tensor-modes

Please update this issue with feedback

I'll send news once I have the version with r=3e-3

**Comment by cbischoff** [comment]
I calculated EE spectra for the CMB sims (SAT only). It looks like the beam sizes don't match what is listed in Table 3-1 of the DSR. In particular, it looks like you are using too small of a beam for 30, 40, 145, 155, and 270 GHz. Beam size looks pretty good for 85, 95, and 220 GHz.

**Comment by zonca** [comment]
thanks @cbischoff, I used beams from `s4sim`, started investigation here: https://github.com/CMB-S4/s4sim/issues/12

**Comment by zonca** [comment]
ok, will do another release, see the plan in #13
