### ISSUE TITLE
Implement atmosphere scaling parameter

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#15]
Currently we only have a boolean flag to include or exclude the atmosphere:

https://github.com/CMB-S4/s4_design_sim_tool/blob/master/s4_reference_design.toml#L33

@keskitalo suggested to add capability of scaling to the atmosphere in the design tool.

* should we have 2 different parameters, one for temperature and one for polarization?
* is a scalar enough or we want to have it scale dependent and use a power spectrum?

**Comment by keskitalo** [comment]
Having separate scalings for temperature and polarization sounds good. The T->P leakage for atmosphere may well be scale-dependent but until there is a model, I would hold on adding that degree of freedom.

**Comment by zonca** [comment]
implemented in #16
