### ISSUE TITLE
Varying observing efficiency by frequency

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#18]
Currently we have 20% observing efficiency for all frequencies:

https://github.com/CMB-S4/s4_design_sim_tool/blob/2821bff66a80c2a6650d7e3fb47e4789ca239f8d/s4_reference_design.toml#L24

However in real instruments higher frequencies have lower efficiency.
We should implement a way to specify observing frequency for each frequency of the tubes and also some standard functional variation (e.g. exponential)

**Comment by jdborrill** [comment]
It's not completely clear that we should do this simply as a
frequency-dependent efficiency factor.

The efficiency cuts implemented by experiments are primarily weather-based,
whereas we are sampling from the full weather distribution but do not have
a data quality/selection step, so in effect we're including "bad" data even
with the efficiency cut. An alternative would therefore be to threshold the
weather sampling, which would have built in frequency dependence.

Julian

**Comment by zonca** [comment]
@keskitalo @cbischoff it looks like this can be implemented in the TOD simulations of atmosphere.
On top of that do we also need it in the tool?

**Comment by cbischoff** [comment]
I think the efficiency factor applies to white noise / detector noise as well. It's tricky to tease it apart, but if 220/270 GHz channels just get cut harder, then that just means less total integration time for those maps.

**Comment by zonca** [comment]
ok, I implemented this in #20 as described in the simulation plan,
see example configuration: https://github.com/CMB-S4/s4_design_sim_tool/pull/20/commits/d5656b2da42522cc0c54f4db8e6c3f71d7b36063

it supports specifying:

* one default value for all channels
* value for individual site/telescope/band
* default by site
* default by site/telescope
