### ISSUE TITLE
Scaling of atmosphere with tubes / telescopes

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#2]
Run the tool with the reference design configuration for all channels with:

* tensor to scalar ratio `r` = 0
* 1e-3

Release to the collaboration

**Comment by jdborrill** [comment]
The two cases for r should be 0 & 3e-3

J

**Comment by zonca** [comment]
@keskitalo do you think we are going to get realization 0 of the atmosphere for all channels sometimes before this Sunday? if so I'll wait and will run maps and do slides based on the full run, otherwise I'll just do an example run with a few channels.

**Comment by keskitalo** [comment]
@zonca realization 0 without a doubt, but hopefully all 8 realizations. I was almost done with the caching when I learned that the reported focal plane radii in the hardware configuration are underestimated. As a result, the simulated atmosphere does not span enough of a volume to fit the lines-of-sight. I'm caching the atmosphere again...

**Comment by zonca** [comment]
@keskitalo I wanted to pick 4 channels (1 per telescope per site) from the atmosphere outputs that you generated.
But I noticed now you deleted them from:

    `/global/cscratch1/sd/keskital/s4sim/reference_tool/out/00000000`

I assume they were broken.
Fortunately I have 1 channel that I saved on my VM and I will use that single SAT channel to demo the tool, even if broken, it will do for now.
We will work on a release after the meeting.

**Comment by keskitalo** [comment]
@zonca Here is the current simulation status:

```
Simulation status:

            Chile                                                                                     Pole                                                                                      
            LAT                                       SAT                                             LAT                                       SAT                                             
flavor      ULFL1 LFL1  LFL2  MFL1  MFL2  HFL1  HFL2  LFS1  LFS2  MFLS1 MFLS2 MFHS1 MFHS2 HFS1  HFS2  ULFL1 LFL1  LFL2  MFL1  MFL2  HFL1  HFL2  LFS1  LFS2  MFLS1 MFLS2 MFHS1 MFHS2 HFS1  HFS2  
noise         8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8     8   
atmosphere    1                             1     1     1     1     1     1     1     1                 1     1     1     1     1     1     1     1     1     1     1     1     1     1     1   
cmb-unlensed  1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1   
cmb-lensing   1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1   
cmb-tensors   1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1   
foreground    1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1  
```

I'm still working to complete the first batch of atmosphere maps. Sorry for the delay.

-R

**Comment by keskitalo** [comment]
@zonca the first realization is in place for all tubes.

**Comment by zonca** [comment]
thanks @keskitalo, I am running them through

**Comment by zonca** [comment]
ok, I got the reference design with `r=3e-3`,

https://132-249-238-90.compute.cloud.sdsc.edu/output//reference-design-r-3e-3/

next `r=0`.

**Comment by zonca** [comment]
ok, `r=0` is at https://132-249-238-90.compute.cloud.sdsc.edu/output/reference-design-r-0/

next, I'll do:

* [ ] cross-checks, plots
* [ ] add documentation about these
* [ ] copy to NERSC
* [ ] announce a proper release

**Comment by zonca** [comment]
@keskitalo @jdborrill 
ok, I don't have the CMB ready, so can't do the full release but it seems like noise is priority.
So I ran noise+atmosphere only.
Maps are ready, I would like to announce release tomorrow or monday.

Here the documentation:
https://github.com/CMB-S4/s4mapbasedsims/tree/master/202004_reference_design

I think we need more docs about noise and atmosphere in the design tool (see #5), then I can summarize in the map release docs.

please send some feedback.

**Comment by jdborrill** [comment]
Hi Andrea,

Before we release more widely we should get Colin's validation.

Thanks,

Julian

**Comment by zonca** [comment]
I am making a check of the white noise level in the maps, using the sensitivity from the table in the DRS.

![Screenshot 2020-04-24 at 00 33 28](https://user-images.githubusercontent.com/383090/80259865-6a219680-863b-11ea-9661-f83f297c3f60.png)

So for LFL1 I took 383 microKsqrt(s).

I made the calculation and it is way off.

![image](https://user-images.githubusercontent.com/383090/80260404-af929380-863c-11ea-9d51-e7609a4380a5.png)

I'm sure I messed up some factor, @keskitalo @cbischoff, would you like to crosscheck my notebook at:

https://gist.github.com/zonca/5d48c8c80ea0a84b01fe66019b96a946

**Comment by zonca** [comment]
one issue is that high noise ell is dominated by the atmosphere.
So if I do the same exercise for the input maps at 10 days, and I take instead the NET from `s4sim` of 177 instead of 383 (see https://github.com/CMB-S4/s4sim/issues/7). I get:

![image](https://user-images.githubusercontent.com/383090/80263153-84ac3d80-8644-11ea-9fa7-10a50a385df0.png)

From the map `C_ell = 1.36e-15`, from the NET `C_ell = 9.76e-16`

next I'll compute the total power spectrum from the input maps and compare with the output to check if the scaling makes sense.

**Comment by zonca** [comment]
ok, I made a full comparison including also the atmosphere:

![image](https://user-images.githubusercontent.com/383090/80264472-1d44bc80-8649-11ea-8b44-956a5d70b9f7.png)

Do you think it looks reasonable?

see the full notebook at https://gist.github.com/zonca/1914abdc08ee1ce00c719fc3aa5f94c7

**Comment by cbischoff** [comment]
Which spectrum is this? TT, EE, BB? If it is a polarization spectrum, then the atmospheric noise is extremely pessimistic. See [this figure](http://bicep.rc.fas.harvard.edu/CMB-S4/analysis_logbook/20180810_noise/index.html#figure5), for example -- BB noise spectrum from ACTpol 2yr result gets to 1e-16 K^2 at ell=500, which is more than an order of magnitude better than the orange curve. 

I'm worried about the assumption that atmospheric noise doesn't integrate down with number of detectors, only with integration time. By this assumption, there is some maximum number of detectors and beyond that number it is pointless to continue scaling up your instrument. Looking at this figure, it seems like the LAT has exceeded this maximum number of detectors by a factor of 1e7 at ell=100 and by a factor of 100 at ell=1000. 

Also, why does the output map power (green curve) greatly exceed the sum of input atmosphere and input noise for ell > 500? Is there some sort of aliasing going on?

**Comment by keskitalo** [comment]
@cbischoff This must be temperature. Without gain and bandpass mismatch, the simulation does not have a mechanism to convert atmosphere-based temperature fluctuations into polarization.

Exactly how we choose to scale the atmospheric noise by detector count is open for discussion. We know that it is very correlated between detectors and won't scale as instrumental noise but beyond that things get complicated. Since the atmospheric noise in polarization is due to detector mismatch, it does help to have many detectors, provided that the mismatch between them is random and not systematic.

Thanks for pointing out the ell > 500 excess. I'm going to see if we can make the spectra align by masking out the poorly sampled edge pixels. If that does not work, we can try using PolSpice instead of anafast to appropriately weight the map according to noise level.

**Comment by keskitalo** [comment]
I should also point out that the spectrum above is for the Chile SAT LF1 case. The fraction of uniformly-weighted sky is 69%.

**Comment by cbischoff** [comment]
Doesn't your atmospheric noise model actually calculate lines of sight through some 3d Kolmogorov distribution? If so, then don't the detectors naturally show partial, but not complete, correlation? Or does the scaling come in because you do the atmospheric sim for just a small number of detectors? (how many?)

**Comment by keskitalo** [comment]
The correlations between detectors within a tube are simulated and accounted for. We only simulate one tube on each telescope. Since the footprint of the tubes on each telescope perfectly overlap, we decided to approximate that the additional tubes on the telescope do not average down the atmosphere. Separate telescopes are treated as independent.

In real life, there probably is some, scale dependent suppression of atmosphere from having more than one tube on the same telescope. We just don't have good models for this yet.

**Comment by tcrawfor** [comment]
> Since the footprint of the tubes on each telescope perfectly overlap, we decided to approximate that the additional tubes on the telescope do not average down the atmosphere.
> 
> 

I'm not sure what this means. Within an individual telescope, the different tubes are both physically and angularly separated. So, depending on where the ray bundles from the individual detectors start expanding, the different tubes might see very different atmosphere.

--
Tom Crawford
University of Chicago
Department of Astronomy & Astrophysics
773-702-1564

**Comment by keskitalo** [comment]
Thanks @tcrawfor . Indeed, this point remains unsettled. In the current model, the majority of the atmospheric power comes from 100m-sized correlated structures a kilometer away from the telescope.  I would expect a high degree of correlation between detectors looking at the same location on the celestial sphere, even if they were on different but adjacent optics tubes. As I said, there will probably be some scale-dependent suppression but we don't have reliable simulations for that yet.

**Comment by tcrawfor** [comment]
But the different tubes in a single telescope are *not* looking at the same location on the celestial sphere. In a given instant, the sky is imaged onto the focal plane, and the physically separated tubes necessarily intercept different portions of that image.

--
Tom Crawford
University of Chicago
Department of Astronomy & Astrophysics
773-702-1564

**Comment by keskitalo** [comment]
That seems like a semantic issue. If the FOV overlap then they, by definition, converge at infinity. The question seems to be if the modest separation of the tubes at the telescope is enough to decorrelate the observations. 

I sent a question to the SAT group for another opinion.  I am out of my depth here and my naive thinking is probably less than helpful.

**Comment by tcrawfor** [comment]
No, this is my fault. I had not read carefully enough, and I was thinking of LAT configuration, in which the different optics tubes in a single telescope can (by definition) not see the same sky.

--
Tom Crawford
University of Chicago
Department of Astronomy & Astrophysics
773-702-1564

**Comment by keskitalo** [comment]
That certainly explains some of the confusion. It still remains that our model of not weighting down the atmosphere by the number of tubes is pessimistic. I am curious to hear from the SAT experts just how pessimistic they find it.

**Comment by jdborrill** [comment]
Although we're using this approach (which I thought we'd discussed and
agreed on the DM telecon) for both LATs and SATs, no?

Julian

**Comment by keskitalo** [comment]
Yes, the LAT tubes are also treated as perfectly correlated but for a very different reason. The FOV of the entire LAT focalplane is so small that the majority of atmospheric fluctuations are extremely correlated across all detectors.

Since the LAT FOVs do not overlap, we could just simulate all tubes and get realistic suppression from more tubes. From looking at ACT and SPT data, I really would not expect much improvement over the current model.  The angular scale of the atmospheric fluctuations is about the size of the LAT FOV.

**Comment by tcrawfor** [comment]
The LAT FOV is 8 degrees in diameter, right? Are you finding nearly perfect correlation all the way across the SPT-3G focal plane? I thought we could detect decorrelation even across the ~1 degree SPT-SZ focal plane, but I can't back that up with hard numbers.

--
Tom Crawford
University of Chicago
Department of Astronomy & Astrophysics
773-702-1564

**Comment by zonca** [comment]
I found a bug in the scaling of the noise, I'm rerunning some maps to make a comparison, I'll open a new issue when I have results. Let's dedicate this issue to scaling of the atmosphere.

**Comment by keskitalo** [comment]
@tcrawfor excellent point. The correlation functions on https://cmb-s4.org/wiki/index.php/Atmospheric_calibration_with_SPT certainly show a modest dependence between correlation strength and separation on the focalplane. And that is only considering separations of less than 2 degrees. Tubes across the CMB-S4 LAT will be more separated and less correlated than our pessimistic model here.

**Comment by zonca** [comment]
@keskitalo do you recommend we change anything in the scaling of the atmosphere for the next run (in #13)?

**Comment by keskitalo** [comment]
@zonca Excellent question! We could decide to adjust the per-tube scaling to better match the map-based SAT simulations. However, there has been little focus on the SAT temperature sims. Much more critical would be to include some amount of detector mismatch and *then* scale the resulting polarized atmosphere. I propose we enable 1% gain mismatch in the sims, keep the tube scaling factors for now. If the resulting BB noise ends up grossly higher than the map-based sims we can revisit the per-tube scaling. @jdborrill ?

**Comment by zonca** [comment]
ok, agreed
