### ISSUE TITLE
Filtered foreground plots

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#3]
@keskitalo I am comparing my simulations and the outputs of the TOD filtering.

`cmbs4_combined_foregrounds_uKCMB_LAT-LFL1_nside4096_0000.fits`

![image](https://user-images.githubusercontent.com/383090/76372638-532d1c00-62fb-11ea-9fe8-bb1d57145175.png)

`chile_foreground_LAT_LFL1_filtered_telescope_all_time_all_bmap.fits`

![image](https://user-images.githubusercontent.com/383090/76372669-663fec00-62fb-11ea-9fac-11e36e083767.png)

can the filtering have such a large effect?

**Comment by keskitalo** [comment]
Absolutely. The filtering will annihilate all large scale temperature structure, which is fine, because there is nothing there to discover after Planck.
