### ISSUE TITLE
web interface

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#4]
@keskitalo @jdborrill 

I have created a first version of the web interface:

http://132-249-238-90.compute.cloud.sdsc.edu/

* To exercise the interface, for now only generates the TOML, doesn't actually run the tool
* It is automatically generated from a standard notebook using ipywidgets, https://github.com/CMB-S4/s4refsimtool/blob/master/05_ui.ipynb
* It is deployed on a Virtual Machine at SDSC, will deploy on Spin for production

TODO next:

* implement moving telescopes from Pole to Chile
* actually run the tool and give the user a link to download the maps

Please take a look and send feedback.

**Comment by tskisner** [comment]
@zonca, the interface looks fine (any idea why the load time was slow?).  How are you launching the notebook?  Directly with jupyter?  If so, then I have everything needed to work on the docker compose file.

**Comment by zonca** [comment]
you run `voila --port 80 --no-browser  05_ui.ipynb`, requirements are `toml` `voila` `ipywidgets`, do not install `toml` with conda but `pip`

**Comment by keskitalo** [comment]
@zonca when I try to follow the link I get an error: "132-249-238-90.compute.cloud.sdsc.edu unexpectedly closed the connection." Is the interface still working for you?

**Comment by zonca** [comment]
Yes, it is working now, can you try again? Maybe test in incognito mode?

**Comment by zonca** [comment]
Also make sure you are not being redirected to https by your browser

**Comment by keskitalo** [comment]
It worked the second time around. Looks really neat! Why are the field names truncated like this:
<img width="412" alt="Screen Shot 2020-03-12 at 11 45 05" src="https://user-images.githubusercontent.com/596250/76556625-23932680-6457-11ea-84cf-0c38191e905b.png">

**Comment by zonca** [comment]
yes, I noticed that, those are default layout settings, I will fix later on

**Comment by zonca** [comment]
@jdborrill @keskitalo @tskisner ok, I have a first version of the simulation web interface:

https://132-249-238-90.compute.cloud.sdsc.edu/

sometimes it hangs and I have to restart the process, not sure what is going on.
It is only running 1 SAT band at Pole for now, I will add the rest once the input maps are all available.

**Comment by zonca** [comment]
focusing on the reference design release first, will get back to work on the web interface later on.
