### ISSUE TITLE
Documentation about atmosphere, noise, scanning

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#5]
We have some docs here https://cmb-s4.github.io/s4_design_sim_tool/#Noise-maps
about the noise maps.
I think it would be useful to know more about all the details with links to the wiki or to the TOAST documentation to get more details, specifically about:

* Atmosphere: model, configuration parameters
* Scanning: minimum elevation, type of scanning strategy, sky area
* Instrument noise: where are the spectra coming from

We can do 2 ways:
* You prepare a page on the wiki or somewhere else specific for this release and I link to it
* You add the documentation https://cmb-s4.github.io/s4_design_sim_tool, this is generated from https://github.com/CMB-S4/s4_design_sim_tool/blob/master/index.ipynb

**Comment by zonca** [comment]
@keskitalo I am almost ready to release the first set of maps, we need some documentation about noise and atmosphere, can you please add some pointers?

**Comment by keskitalo** [comment]
@zonca Sorry, this fell in the cracks. I'll try to address it tomorrow.

**Comment by keskitalo** [comment]
I added details here: https://cmb-s4.org/wiki/index.php/Reference_design_simulation_tool
