### ISSUE TITLE
unlensed and lensed cmb maps

### ISSUE THREAD

**Issue by ajvanengelen** [CMB-S4/s4_design_sim_tool#6]
Currently the code contains a sliding knob that does a linear combination between the lensed and unlensed CMB maps.  In my view the code should return either the lensed map or the unlensed one -- lensing is a nonlinear operation and doing a simple linear combination between the two is not a valid approximation.  Delensing is being explored in detail by the appropriate working groups, and they will provide the delensed CMB maps for analysis groups who need them.

I think this should be changed to a binary switch, with lensing either on or off.

**Comment by zonca** [comment]
ok, I'll implement this.

**Comment by jdborrill** [comment]
Sorry to be late - I'd forgotten I'd meant to respond.

I'd like to keep the slider, while acknowledging its limitations. Many of
the WGs (Low-ell BB in particular) want maps that have at least an
approximation of delensing residuals without having to actually run
delensing codes, and are using exactly this technique to mock that up. In
the longer term we definitely want the delensing to be done, but for now we
still need this approximate method.

Julian

**Comment by ajvanengelen** [comment]
Hi Julian,
That is true, low-ell BB might be the one place where this is an OK approximation (since the unlensed map is zero, neglecting tensors).  I'd been thinking of the temperature and E maps at high ell.
Alex

**Comment by zonca** [comment]
ok, thanks, adding a notice about this in the docs
