### ISSUE TITLE
Noise and atmosphere simulations comparison

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#7]
@keskitalo @cbischoff 

Ok, I fixed the bugs in the noise and atmosphere scaling, now I believe the results are consistent.

I am using 177 microK * sqrt(s) for the white noise level both in T and P.

The spectra below are pseudospectra done with anafast, just corrected by the sky fraction, no mask deconvolution.
I scaled the input noise, the input atmosphere and the white noise level to the full experiment length so I could compare them all.

![TT](https://user-images.githubusercontent.com/383090/80411918-d68dd700-8881-11ea-8416-2081d8f2d42b.png)
![EE](https://user-images.githubusercontent.com/383090/80411921-d7bf0400-8881-11ea-9660-74ddc979d599.png)
![BB](https://user-images.githubusercontent.com/383090/80411922-d7bf0400-8881-11ea-84f7-d4239c06e252.png)

**Comment by zonca** [comment]
For SAT instead I have a large discrepancy:

## SAT HFS1

I take the input cl for 10 days I multiply by:

    (10 * simulations_efficiency / 8)

so I get noise for 1 tube and 1 day at 100% efficiency, and the full focal plane (8 is the thinning factor from the simulations).
Then I scale to 7 years at 20% efficiency and all tubes:
 
    (7 * 365.25 * .2) / 4

For the white noise level instead:

    net = 747.0 * u.uK * u.s ** .5
    num_detectors_per_tube = 8438
    num_tubes = 4
    integration_time_per_detector_per_pixel = (7 * u.year * .2/num_hit_pixels).to(u.s)
    integration_time_per_pixel= integration_time_per_detector_per_pixel*num_detectors_per_tube*num_tubes
    std = net / np.sqrt(integration_time_per_pixel)
    white_noise_cl = pixarea * std**2

and I get a white noise Cl of: 3.0707861e−19 K^2

![SAT-HFS1_pole_EE](https://user-images.githubusercontent.com/383090/80427543-d8b15f00-889c-11ea-8d92-73f5db92bda9.png)
![SAT-HFS1_pole_BB](https://user-images.githubusercontent.com/383090/80427546-d949f580-889c-11ea-8ab4-04ecf527d939.png)

@keskitalo any suggestion of what could be wrong?

**Comment by keskitalo** [comment]
Wow. Is that about a 3 orders of a magnitude difference? Has to be something obvious. We should start by estimating the single detector noise level from the simulated maps and see if it has anything to do with the value in the hardware map.

**Comment by zonca** [comment]
ok, I'll do that and post here

**Comment by zonca** [comment]
@keskitalo 

`cl_full` is `anafast` of: `/global/cscratch1/sd/keskital/s4sim/reference_tool/out/00000000/pole_noise_SAT_HFS1_filtered_telescope_all_time_all_bmap.fits`

    std_per_pixel = np.sqrt(cl_full[1][500:].mean() / sky_fraction / pixarea)
    0.0004924752646626618

which is consistent with:

    full[1][full[1] != hp.UNSEEN].std()
    0.0004347912651196421

then I get the `integration_time_per_pixel` I computed in the post above, which is: `7259059.1 s`

    std_per_pixel * u.K * np.sqrt(integration_time_per_pixel)
    1.3268584 K s ^ 0.5

instead of `net = 747.0 * u.uK * u.s ** .5`

**Comment by keskitalo** [comment]
I have the hitmap for your case evaluated here: `/global/cscratch1/sd/keskital/s4sim/reference_tool/out2/00000000/pole_noise_SAT_HFS1_filtered_telescope_all_time_all_hmap.fits`

**Comment by zonca** [comment]
what is the sample rate?

**Comment by keskitalo** [comment]
20Hz

**Comment by zonca** [comment]
ok, I think they are consistent:

    hits.sum()/1e9
    7.31

    total_hits = 10 * u.d * simulations_efficiency * num_detectors_per_tube / 8 * (20 * u.Hz)
    8.44e9

**Comment by zonca** [comment]
@keskitalo if I take the `wcov` from Madam instead and I do:

    std_wcov = np.sqrt(wcov[5] * hits)

Shouldn't I get the NET? `np.median(std_wcov[std_wcov != 0])` is `0.0035`

**Comment by keskitalo** [comment]
The hardware map has `NET=747.0uK/sqrt(Hz)`. With your `sigma=0.0035K_CMB` I get `NET=sigma/sqrt(fsample)=782.6uK`. Seems perfectly consistent to me.

**Comment by zonca** [comment]
yes, right, hitmap and wcov are fine. It is the noise in the binned map which seems way too high, or I've messed up the calculations somewhere, I'll crosscheck again.

**Comment by zonca** [comment]
If I get `C_ell` of the noise from the wcov for the full sky, as:

    wcov[3].mean()*pixarea
    4.7e-14 K ^ 2

is consistent with:

    cl_full[1][500:].mean()
    6.33e-14 K ^ 2

**Comment by zonca** [comment]
from the DSR I have `num_detectors_per_tube = 8438`, where do I find the number of detectors in `s4sim`?

**Comment by keskitalo** [comment]
From `/global/cscratch1/sd/keskital/s4sim/reference_tool/logs/pole_noise_SAT_HFS1.log` it looks like there were 1076 detectors (line 126) with `thinfp=8`.

**Comment by zonca** [comment]
still something wrong, let's do without scaling, just the TOAST simulations:

* White noise from TOAST wcov `np.mean(wcov[wcov !=0]) * pixarea` is `7.2e-13`
* The simulated noise, EE with anafast just corrected for the sky fraction is `9e-13`
* The issue is the estimate from NET which is `1e-15`
 
        white_noise_cl_sims = pixarea * (747e-6)**2 / (
            10 * (24*3600) * 0.4629 * 1076 / num_hit_pixels
        ) 
* Same using the hitmap `1.3e-15`
       
        white_noise_cl_sims = pixarea * net**2 * (20 * u.Hz) / (
             hits[hits > 0].mean() 
        ) 

![image](https://user-images.githubusercontent.com/383090/80452721-b12db700-88db-11ea-86be-9317f6d0ceec.png)

**Comment by keskitalo** [comment]
I think I know what is going on. TOAST modulates the raw detector sensitivity with the observing elevation. Increased atmospheric loading at low observing elevation reduces sensitivity. The model is
```
NET(el) = (A / sin(el) + C) * NET(45)
```
and the hardware map values for the HFS1 band are
```
A = 0.30
C = 0.58
```

This gives the following curve:

![elevation_noise](https://user-images.githubusercontent.com/596250/80498030-1905f100-8920-11ea-9d69-68ee9504b4c5.png)

From the Pole, lower Celestial latitude always means lower observing elevation so the raw NET estimate systematically underestimates the noise below 45 degrees:

![noise_estimate](https://user-images.githubusercontent.com/596250/80496474-1b674b80-891e-11ea-8977-bcbb856893cd.png)

This is only considering about 2/3 of the most hit pixels. If you consider all hit pixels, you find:

![noise_estimate 2](https://user-images.githubusercontent.com/596250/80498873-19eb5280-8921-11ea-8480-97229d395ea0.png)

I am guessing that your power spectra are completely driven by those super noisy `DEC > -30` pixels where the NET(45) underestimates the noise by as much as X40.  

`Anafast` is clearly not suited for analyzing so unevenly distributed integration depth maps. At the very least, the noisiest pixels should be masked out.

**Comment by zonca** [comment]
thanks @keskitalo!
masking the 10% pixels with higher wcov and use median instead of mean to get the noise from wcov is enough to have a rough consistency check:

![SAT-HFS1_pole_EE (1)](https://user-images.githubusercontent.com/383090/80510968-54102080-8930-11ea-9f78-5a3b4488ec9a.png)
![SAT-HFS1_pole_BB (1)](https://user-images.githubusercontent.com/383090/80510972-55414d80-8930-11ea-9ed7-998a5f4ff8d7.png)

ok, I'll go ahead and run all the channels through
