### ISSUE TITLE
Validation of reference design noise + atmosphere release

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#8]
SAT maps are available, LAT being finalized,
see https://github.com/CMB-S4/s4mapbasedsims/tree/master/202004_reference_design
for details and path at NERSC.

I've done a rough consistency check for LAT and SAT, see https://github.com/CMB-S4/s4_design_sim_tool/issues/7

@cbischoff could you please make a deeper validation and report results here (or provide a link to wiki)

/cc @jdborrill @keskitalo

**Comment by zonca** [comment]
ok, LAT maps are available as well

**Comment by zonca** [comment]
> summarizing email thread here for easier reference

@cbischoff ran spectra, available temporarily here:
http://bicep.rc.fas.harvard.edu/cbischoff/DM_AWG_noise/

Suggested there were issues with the maps, which @keskitalo identified as:

1) The TOD was not cleared between MC realizations, causing the noise to increase iteration after iteration.
2) The focalplane thinning factor was not consistent.

@keskitalo reran the input maps, @zonca reran the design simulation tool, the updated maps are available at:

    /global/cscratch1/sd/zonca/cmbs4/s4refsimtool/reference_design_nosky_7splits

@cbischoff can you please run your validation again?

**Comment by cbischoff** [comment]
I have updated that posting, added text, and moved it to a permanent location.
http://bicep.rc.fas.harvard.edu/CMB-S4/analysis_logbook/20200519_DM_AWG_noise/
(also linked from the [CMB-S4 wiki Simulation and Forecasting Logbook](https://cmb-s4.org/wiki/index.php/Simulation_and_Forecasting_Logbook))

**Comment by keskitalo** [comment]
Thanks @cbischoff . It appears that even with the corrections, the 145GHz BB noise is 5X lower in the DM sim. That is a pretty glaring discrepancy.

**Comment by keskitalo** [comment]
In Colin's table, the DSR and low-ell-BB noise bias at 145GHz is 15% lower than at 155GHz. In the DM sim, the difference in 49%. This is entirely consistent with the NET levels in https://github.com/CMB-S4/s4sim/blob/master/s4sim/hardware/config.py (238 and 331). Do the DSR noise levels include an extra noise component not present in the NET? If not, why are the NET levels so different?

**Comment by zonca** [comment]
rerun everything, see #13
