### ISSUE TITLE
Process hitmaps and noise maps

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#9]
@keskitalo produced hitmaps and white noise covariance maps:

`/global/cscratch1/sd/keskital/s4sim/reference_tool/out2/00000000`

as part of the `s4_design_sim_tool` run, also apply appropriate scaling to those maps and release them together with the other maps.

**Comment by jdborrill** [comment]
I'm confused about "also apply appropriate scaling to those maps and add
them to the output maps."

Julian

**Comment by zonca** [comment]
@jdborrill bad phrasing, fixing that!

**Comment by zonca** [comment]
@keskitalo I implemented this, and my tests fail.

Using `/global/cscratch1/sd/keskital/s4sim/reference_tool/out_v1/`
`00000000/pole_noise_SAT_HFS1_filtered_telescope_all_time_all_hmap.fits`

If I do:

```
sampling_rate = input_map.sum() 
sampling_rate /= 10 * 24 * 3600 * simulations_observing_efficiency[site.lower()][telescope]
sampling_rate /= 8438 # HF detectors per tube from DSR
sampling_rate *= 8 # focal plane thinning factor
```

observing efficiency is 0.4629

I get ~17.3 Hz instead of 100 Hz (https://github.com/CMB-S4/s4sim/issues/14)

Can you crosscheck my factors? in particular number of detectors, I got it from the DSR is your number the same?

**Comment by keskitalo** [comment]
As I said on the other thread, you would expect to find 20Hz, not 100Hz. However, some efficiency is lost in the turnarounds that is not accounted for in your efficiency factor.

This does actually raise an important point. Since the simulation tool already includes an overall efficiency factor, we should *not* be suppressing the efficiency based on the turnarounds. I went ahead and calculated the efficiency factors for all cases:

```
Chile SAT 0.8656164351851852
Chile LAT 0.917306712962963
Pole  SAT 0.3931149305555555
Pole  LAT 0.321544537037037
````

I think you should update the current efficiency factors in the tool and rerun. Otherwise we are simulating an extra 10% hit in observing efficiency.

**Comment by zonca** [comment]
thanks,
so now with:

```
sampling_rate = input_map.sum() 
sampling_rate /= 10 * 24 * 3600 * 0.3931149305555555
sampling_rate /= 8438 # HF detectors per tube
sampling_rate *= 8 # focal plane thinning factor
```

I get 20.4 Hz which is good.

When I compute the full hitmap, should I account for the factor of 5 between simulation sampling rate (20 Hz) and experiment sampling rate (100 Hz) or you weighted the instrument noise to already compensate for that?

**Comment by keskitalo** [comment]
The NETs are independent of the sampling frequency. So are the `*_wcov.fits` white noise covariance matrices. It would be great if you could scale the hit maps but I doubt it will make any difference to most users.

**Comment by tcrawfor** [comment]
Sorry, Reijo, what do these "efficiencies" represent? How are they calculated? Anything with a 92% overall efficiency rings some pretty strong alarm bells.

--
Tom Crawford
University of Chicago
Department of Astronomy & Astrophysics
773-702-1564

**Comment by keskitalo** [comment]
@tcrawfor This is the integration time in our simulation divided by 10 days, the nominal simulation length. The idea is that the user is already setting the overall efficiency (default is 0.2), and we don't want to add any other efficiency factors on top of it.

**Comment by zonca** [comment]
@keskitalo now I am checking the `wcov` matrices.

I am working with `HFS1`, so checking in `config.py` in the Pull Request https://github.com/CMB-S4/s4sim/pull/8,
the NET should be `747 uK*sqrt(s)`, same as the DSR:

https://github.com/CMB-S4/s4sim/blob/c2732f0e8fb014392cef664ff4213bf47133aaac/s4sim/hardware/config.py#L546

I load the `cc(2,2)` column, which should be EE noise covariance.

`input_map` below is the hitmap

![image](https://user-images.githubusercontent.com/383090/86277265-4757b500-bb8b-11ea-9913-7e12381d8b79.png)

It looks like I'm off by a factor of sqrt(2), do you know where that should be coming from?

(btw, how beautiful is `astropy.units`?)

**Comment by keskitalo** [comment]
That is exactly what you would expect. The NET is given for intensity and solving for polarization adds a factor of `sqrt(2)`. In other words, `Var(Q) = Var(U) = 2 x Var(I)` for an experiment with ideal polarization efficiency and sampling of position angles.

As for `astropy.units`, just imagine how cool it was if `healpy.read_map()` got the units from the FITS header and returned `HealpixMap` objects that were aware of their pixel ordering and units?

**Comment by zonca** [comment]
> As for `astropy.units`, just imagine how cool it was if `healpy.read_map()` got the units from the FITS header and returned `HealpixMap` objects that were aware of their pixel ordering and units?

definitely! at some point in the next 10 years I'll implement that!

**Comment by zonca** [comment]
@keskitalo also PySM has a wrapper around `read_map` that applies units read from headers: https://pysm3.readthedocs.io/en/latest/api/pysm3.read_map.html#pysm3.read_map

**Comment by zonca** [comment]
ok, this is implemented and crosschecked, see details here: https://cmb-s4.github.io/s4_design_sim_tool/hitmap_wcov/

now I will implement support in the command line client, execute it and add hitmaps and wcov matrices to the release https://github.com/CMB-S4/s4mapbasedsims/tree/master/202006_reference_design

**Comment by zonca** [comment]
ok, implemented support in the command line client and executed the simulations again. See #13

**Comment by zonca** [comment]
@keskitalo the validation works with 8438 detectors for the HFS1 band, which is the DSR number,
while in the spreadsheet https://docs.google.com/spreadsheets/d/1X0x8wYhjHdI_WPjhgbtyVlVQrX86tTgxgqEUhan2Hxg/edit?pli=1#gid=1404929524 the number of detectors is 8594.

Can you please give me a table of the number of detectors per band that you used so I can use that for validation? Is there a versioned reference for the instrument model that you used?

**Comment by keskitalo** [comment]
@smsimon should have that information. The DSR detector counts for the HF bands had an error in them that is fixed in the spreadsheet and in `s4sim`.

**Comment by smsimon** [comment]
@zonca the number of HFS pixels went up because the DSR was rounding on the number of pixels on the partial wafer. In a real layout, the HFS partial wafers get an additional 13 pixels (26 detectors for each frequency). Each HFS optics tube has 6 partial wafers. 8438+26*6=8594.

**Comment by zonca** [comment]
ok, good, thank you both, with the fixed number consistency of hitmaps and wcov is improved. Number of detectors per tube in now in my export of the instrument model, see https://github.com/CMB-S4/s4sim/issues/15
